---
- name: DotFiles Config
  hosts: localhost
  become: true
  connection: local

  pre_tasks:
    - name: Load Initial Facts
      ansible.builtin.import_tasks: pre_tasks/facts.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ (ansible_run_tags | select('ne', 'all') | list) or (default_roles | difference(exclude_roles | default([])) | sort) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

