---
- name: media-tools | install ffmpeg (Arch)
  ansible.builtin.pacman:
    name: ffmpeg
    state: present
  tags:
    - media-tools
    - ffmpeg
    - packages

- name: media-tools | install libvips (Arch)
  ansible.builtin.pacman:
    name: vips
    state: present
  tags:
    - media-tools
    - libvips
    - packages
