---
- name: media-tools | install ffmpeg (Ubuntu)
  ansible.builtin.apt:
    name: ffmpeg
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - media-tools
    - ffmpeg
    - packages

- name: media-tools | install libvips (Ubuntu)
  ansible.builtin.apt:
    name: libvips-tools
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - media-tools
    - libvips
    - packages
